import type { InsertCountry } from "@workspace/db";

export const COUNTRIES: InsertCountry[] = [
  // Europe
  { code: "DE", name: "Germany", nameAr: "ألمانيا", flag: "🇩🇪", region: "Europe", description: "وجهة رائدة للمنح الدراسية والهجرة المهنية، تقدم تعليماً مجانياً في جامعاتها الحكومية وفرص عمل واسعة.", latitude: 51.1657, longitude: 10.4515 },
  { code: "FR", name: "France", nameAr: "فرنسا", flag: "🇫🇷", region: "Europe", description: "تعليم عريق ومنح متعددة وبرامج هجرة واضحة للمهارات والكفاءات.", latitude: 46.2276, longitude: 2.2137 },
  { code: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة", flag: "🇬🇧", region: "Europe", description: "جامعات مرموقة ومنح شيفنينغ ومسارات تأشيرة المهارات.", latitude: 55.3781, longitude: -3.4360 },
  { code: "IT", name: "Italy", nameAr: "إيطاليا", flag: "🇮🇹", region: "Europe", description: "تعليم بأسعار معقولة ومنح حكومية وفرص هجرة موسمية ومهنية.", latitude: 41.8719, longitude: 12.5674 },
  { code: "ES", name: "Spain", nameAr: "إسبانيا", flag: "🇪🇸", region: "Europe", description: "منح إيراسموس وتأشيرات الرحالة الرقميين وبرامج الإقامة.", latitude: 40.4637, longitude: -3.7492 },
  { code: "NL", name: "Netherlands", nameAr: "هولندا", flag: "🇳🇱", region: "Europe", description: "جامعات بأعلى التصنيفات وبرنامج البحث العلمي وفرص هجرة المهارات.", latitude: 52.1326, longitude: 5.2913 },
  { code: "BE", name: "Belgium", nameAr: "بلجيكا", flag: "🇧🇪", region: "Europe", description: "مركز المؤسسات الأوروبية ومنح متخصصة.", latitude: 50.5039, longitude: 4.4699 },
  { code: "SE", name: "Sweden", nameAr: "السويد", flag: "🇸🇪", region: "Europe", description: "منح حكومية ودراسات عليا متقدمة وبرامج هجرة المهارات.", latitude: 60.1282, longitude: 18.6435 },
  { code: "NO", name: "Norway", nameAr: "النرويج", flag: "🇳🇴", region: "Europe", description: "تعليم مجاني وفرص بحثية ومستوى معيشي مرتفع.", latitude: 60.4720, longitude: 8.4689 },
  { code: "FI", name: "Finland", nameAr: "فنلندا", flag: "🇫🇮", region: "Europe", description: "نظام تعليمي رائد عالمياً ومنح للماجستير والدكتوراه.", latitude: 61.9241, longitude: 25.7482 },
  { code: "DK", name: "Denmark", nameAr: "الدنمارك", flag: "🇩🇰", region: "Europe", description: "منح حكومية وبرنامج البطاقة الخضراء للمهارات.", latitude: 56.2639, longitude: 9.5018 },
  { code: "CH", name: "Switzerland", nameAr: "سويسرا", flag: "🇨🇭", region: "Europe", description: "جامعات بحثية رائدة ومنح فيدرالية للطلاب الأجانب.", latitude: 46.8182, longitude: 8.2275 },
  { code: "AT", name: "Austria", nameAr: "النمسا", flag: "🇦🇹", region: "Europe", description: "منح OEAD وبرامج بحثية متعددة.", latitude: 47.5162, longitude: 14.5501 },
  { code: "PT", name: "Portugal", nameAr: "البرتغال", flag: "🇵🇹", region: "Europe", description: "تأشيرة الرحالة الرقميين وبرامج هجرة مرنة.", latitude: 39.3999, longitude: -8.2245 },
  { code: "IE", name: "Ireland", nameAr: "أيرلندا", flag: "🇮🇪", region: "Europe", description: "منح حكومية وفرص عمل في قطاع التكنولوجيا.", latitude: 53.4129, longitude: -8.2439 },
  { code: "PL", name: "Poland", nameAr: "بولندا", flag: "🇵🇱", region: "Europe", description: "منح Banach وتعليم بأسعار منخفضة.", latitude: 51.9194, longitude: 19.1451 },
  { code: "CZ", name: "Czech Republic", nameAr: "التشيك", flag: "🇨🇿", region: "Europe", description: "منح حكومية وتعليم مجاني باللغة التشيكية.", latitude: 49.8175, longitude: 15.4730 },
  { code: "HU", name: "Hungary", nameAr: "المجر", flag: "🇭🇺", region: "Europe", description: "منح Stipendium Hungaricum للطلاب الدوليين.", latitude: 47.1625, longitude: 19.5033 },
  { code: "GR", name: "Greece", nameAr: "اليونان", flag: "🇬🇷", region: "Europe", description: "تأشيرة Golden Visa وفرص دراسية متنوعة.", latitude: 39.0742, longitude: 21.8243 },
  { code: "RO", name: "Romania", nameAr: "رومانيا", flag: "🇷🇴", region: "Europe", description: "تعليم اقتصادي وفرص عمل في الاتحاد الأوروبي.", latitude: 45.9432, longitude: 24.9668 },
  { code: "BG", name: "Bulgaria", nameAr: "بلغاريا", flag: "🇧🇬", region: "Europe", description: "منح حكومية ورسوم منخفضة وعضوية في الاتحاد الأوروبي.", latitude: 42.7339, longitude: 25.4858 },
  { code: "HR", name: "Croatia", nameAr: "كرواتيا", flag: "🇭🇷", region: "Europe", description: "وجهة ناشئة للدراسة والعمل في أوروبا.", latitude: 45.1000, longitude: 15.2000 },
  { code: "RS", name: "Serbia", nameAr: "صربيا", flag: "🇷🇸", region: "Europe", description: "منح حكومية وتعليم بأسعار معقولة.", latitude: 44.0165, longitude: 21.0059 },
  { code: "EE", name: "Estonia", nameAr: "إستونيا", flag: "🇪🇪", region: "Europe", description: "الإقامة الإلكترونية وفرص للرحالة الرقميين.", latitude: 58.5953, longitude: 25.0136 },
  { code: "LV", name: "Latvia", nameAr: "لاتفيا", flag: "🇱🇻", region: "Europe", description: "تعليم بأسعار منخفضة في الاتحاد الأوروبي.", latitude: 56.8796, longitude: 24.6032 },
  { code: "LT", name: "Lithuania", nameAr: "ليتوانيا", flag: "🇱🇹", region: "Europe", description: "منح حكومية للماجستير والدكتوراه.", latitude: 55.1694, longitude: 23.8813 },
  { code: "SK", name: "Slovakia", nameAr: "سلوفاكيا", flag: "🇸🇰", region: "Europe", description: "منح حكومية لدراسة الطب والهندسة.", latitude: 48.6690, longitude: 19.6990 },
  { code: "SI", name: "Slovenia", nameAr: "سلوفينيا", flag: "🇸🇮", region: "Europe", description: "منح للدراسات العليا وتعليم متطور.", latitude: 46.1512, longitude: 14.9955 },
  { code: "LU", name: "Luxembourg", nameAr: "لوكسمبورغ", flag: "🇱🇺", region: "Europe", description: "فرص هجرة في القطاع المالي والبحثي.", latitude: 49.8153, longitude: 6.1296 },
  { code: "IS", name: "Iceland", nameAr: "آيسلندا", flag: "🇮🇸", region: "Europe", description: "منح للدراسات الشمالية وفرص بحثية.", latitude: 64.9631, longitude: -19.0208 },
  { code: "MT", name: "Malta", nameAr: "مالطا", flag: "🇲🇹", region: "Europe", description: "تعليم باللغة الإنجليزية وفرص هجرة استثمارية.", latitude: 35.9375, longitude: 14.3754 },
  { code: "CY", name: "Cyprus", nameAr: "قبرص", flag: "🇨🇾", region: "Europe", description: "تعليم باللغة الإنجليزية ضمن الاتحاد الأوروبي.", latitude: 35.1264, longitude: 33.4299 },

  // North America
  { code: "US", name: "United States", nameAr: "الولايات المتحدة", flag: "🇺🇸", region: "North America", description: "أكبر سوق للمنح الدراسية والفرص المهنية والتأشيرات المتنوعة.", latitude: 37.0902, longitude: -95.7129 },
  { code: "CA", name: "Canada", nameAr: "كندا", flag: "🇨🇦", region: "North America", description: "وجهة هجرة رائدة عبر Express Entry وProvincial Nominee Programs.", latitude: 56.1304, longitude: -106.3468 },
  { code: "MX", name: "Mexico", nameAr: "المكسيك", flag: "🇲🇽", region: "North America", description: "منح للدراسة في أمريكا اللاتينية وبرامج تبادل ثقافي.", latitude: 23.6345, longitude: -102.5528 },

  // South / Latin America
  { code: "BR", name: "Brazil", nameAr: "البرازيل", flag: "🇧🇷", region: "South America", description: "منح Science Without Borders وفرص دراسية في أكبر اقتصاد لاتيني.", latitude: -14.2350, longitude: -51.9253 },
  { code: "AR", name: "Argentina", nameAr: "الأرجنتين", flag: "🇦🇷", region: "South America", description: "تعليم عالٍ مجاني تقريباً وفرص هجرة سهلة.", latitude: -38.4161, longitude: -63.6167 },
  { code: "CL", name: "Chile", nameAr: "تشيلي", flag: "🇨🇱", region: "South America", description: "منح حكومية وفرص دراسية في أمريكا الجنوبية.", latitude: -35.6751, longitude: -71.5430 },
  { code: "CO", name: "Colombia", nameAr: "كولومبيا", flag: "🇨🇴", region: "South America", description: "منح للدراسة باللغة الإسبانية ووجهة ناشئة.", latitude: 4.5709, longitude: -74.2973 },
  { code: "PE", name: "Peru", nameAr: "بيرو", flag: "🇵🇪", region: "South America", description: "فرص دراسية وفرص للعمل في الأبحاث الأثرية.", latitude: -9.1900, longitude: -75.0152 },
  { code: "UY", name: "Uruguay", nameAr: "أوروغواي", flag: "🇺🇾", region: "South America", description: "بلد مستقر مع فرص هجرة هادئة.", latitude: -32.5228, longitude: -55.7658 },
  { code: "EC", name: "Ecuador", nameAr: "الإكوادور", flag: "🇪🇨", region: "South America", description: "تأشيرات مرنة وتكلفة معيشة منخفضة.", latitude: -1.8312, longitude: -78.1834 },
  { code: "PY", name: "Paraguay", nameAr: "باراغواي", flag: "🇵🇾", region: "South America", description: "برنامج إقامة دائمة سهل وضرائب منخفضة.", latitude: -23.4425, longitude: -58.4438 },
  { code: "BO", name: "Bolivia", nameAr: "بوليفيا", flag: "🇧🇴", region: "South America", description: "تكلفة معيشة منخفضة وفرص دراسية.", latitude: -16.2902, longitude: -63.5887 },
  { code: "VE", name: "Venezuela", nameAr: "فنزويلا", flag: "🇻🇪", region: "South America", description: "فرص دراسية في الجامعات الحكومية.", latitude: 6.4238, longitude: -66.5897 },
  { code: "CR", name: "Costa Rica", nameAr: "كوستاريكا", flag: "🇨🇷", region: "North America", description: "وجهة شعبية للرحالة الرقميين وتأشيرات الإقامة.", latitude: 9.7489, longitude: -83.7534 },
  { code: "PA", name: "Panama", nameAr: "بنما", flag: "🇵🇦", region: "North America", description: "تأشيرة Friendly Nations لجنسيات معينة.", latitude: 8.5380, longitude: -80.7821 },
  { code: "DO", name: "Dominican Republic", nameAr: "الدومينيكان", flag: "🇩🇴", region: "North America", description: "وجهة سياحية وفرص استثمار ومعيشة.", latitude: 18.7357, longitude: -70.1627 },
  { code: "JM", name: "Jamaica", nameAr: "جامايكا", flag: "🇯🇲", region: "North America", description: "تعليم باللغة الإنجليزية في الكاريبي.", latitude: 18.1096, longitude: -77.2975 },
  { code: "CU", name: "Cuba", nameAr: "كوبا", flag: "🇨🇺", region: "North America", description: "منح للدراسات الطبية والعلمية.", latitude: 21.5218, longitude: -77.7812 },
  { code: "GT", name: "Guatemala", nameAr: "غواتيمالا", flag: "🇬🇹", region: "North America", description: "تكلفة معيشة منخفضة وثقافة غنية.", latitude: 15.7835, longitude: -90.2308 },
  { code: "HN", name: "Honduras", nameAr: "هندوراس", flag: "🇭🇳", region: "North America", description: "فرص دراسية واستثمار في أمريكا الوسطى.", latitude: 15.2000, longitude: -86.2419 },
  { code: "SV", name: "El Salvador", nameAr: "السلفادور", flag: "🇸🇻", region: "North America", description: "تكلفة منخفضة وبيئة استثمار صاعدة.", latitude: 13.7942, longitude: -88.8965 },
  { code: "NI", name: "Nicaragua", nameAr: "نيكاراغوا", flag: "🇳🇮", region: "North America", description: "فرص دراسية ومعيشة بأسعار معقولة.", latitude: 12.8654, longitude: -85.2072 },

  // Asia
  { code: "JP", name: "Japan", nameAr: "اليابان", flag: "🇯🇵", region: "Asia", description: "منح MEXT الحكومية وفرص بحثية في التكنولوجيا.", latitude: 36.2048, longitude: 138.2529 },
  { code: "KR", name: "South Korea", nameAr: "كوريا الجنوبية", flag: "🇰🇷", region: "Asia", description: "منح GKS الكورية وبرامج تبادل ثقافي.", latitude: 35.9078, longitude: 127.7669 },
  { code: "CN", name: "China", nameAr: "الصين", flag: "🇨🇳", region: "Asia", description: "منح CSC الحكومية الصينية ومنح Confucius.", latitude: 35.8617, longitude: 104.1954 },
  { code: "IN", name: "India", nameAr: "الهند", flag: "🇮🇳", region: "Asia", description: "منح ICCR وفرص دراسية في تخصصات متعددة.", latitude: 20.5937, longitude: 78.9629 },
  { code: "SG", name: "Singapore", nameAr: "سنغافورة", flag: "🇸🇬", region: "Asia", description: "جامعات عالمية ومنح حكومية وتأشيرات للمهارات.", latitude: 1.3521, longitude: 103.8198 },
  { code: "MY", name: "Malaysia", nameAr: "ماليزيا", flag: "🇲🇾", region: "Asia", description: "تعليم باللغة الإنجليزية وبرنامج MM2H للهجرة.", latitude: 4.2105, longitude: 101.9758 },
  { code: "ID", name: "Indonesia", nameAr: "إندونيسيا", flag: "🇮🇩", region: "Asia", description: "منح Darmasiswa الحكومية ووجهة ناشئة.", latitude: -0.7893, longitude: 113.9213 },
  { code: "TH", name: "Thailand", nameAr: "تايلاند", flag: "🇹🇭", region: "Asia", description: "تأشيرات المهارات الذكية وفرص هجرة طويلة الأمد.", latitude: 15.8700, longitude: 100.9925 },
  { code: "VN", name: "Vietnam", nameAr: "فيتنام", flag: "🇻🇳", region: "Asia", description: "اقتصاد صاعد وفرص دراسية بأسعار منخفضة.", latitude: 14.0583, longitude: 108.2772 },
  { code: "PH", name: "Philippines", nameAr: "الفلبين", flag: "🇵🇭", region: "Asia", description: "تعليم باللغة الإنجليزية بأسعار معقولة.", latitude: 12.8797, longitude: 121.7740 },
  { code: "PK", name: "Pakistan", nameAr: "باكستان", flag: "🇵🇰", region: "Asia", description: "منح حكومية للتبادل الإسلامي والآسيوي.", latitude: 30.3753, longitude: 69.3451 },
  { code: "BD", name: "Bangladesh", nameAr: "بنغلاديش", flag: "🇧🇩", region: "Asia", description: "فرص دراسية اقتصادية في جنوب آسيا.", latitude: 23.6850, longitude: 90.3563 },
  { code: "LK", name: "Sri Lanka", nameAr: "سريلانكا", flag: "🇱🇰", region: "Asia", description: "منح للدراسات البوذية والآسيوية.", latitude: 7.8731, longitude: 80.7718 },
  { code: "NP", name: "Nepal", nameAr: "نيبال", flag: "🇳🇵", region: "Asia", description: "وجهة للمغامرات الجبلية والدراسات الثقافية.", latitude: 28.3949, longitude: 84.1240 },
  { code: "KH", name: "Cambodia", nameAr: "كمبوديا", flag: "🇰🇭", region: "Asia", description: "تأشيرات تجارية مرنة وتكلفة معيشة منخفضة.", latitude: 12.5657, longitude: 104.9910 },
  { code: "LA", name: "Laos", nameAr: "لاوس", flag: "🇱🇦", region: "Asia", description: "وجهة هادئة وفرص هجرة بسيطة.", latitude: 19.8563, longitude: 102.4955 },
  { code: "MM", name: "Myanmar", nameAr: "ميانمار", flag: "🇲🇲", region: "Asia", description: "اقتصاد ناشئ وفرص دراسية.", latitude: 21.9162, longitude: 95.9560 },
  { code: "MN", name: "Mongolia", nameAr: "منغوليا", flag: "🇲🇳", region: "Asia", description: "فرص بحثية في الجيولوجيا والتاريخ.", latitude: 46.8625, longitude: 103.8467 },
  { code: "KZ", name: "Kazakhstan", nameAr: "كازاخستان", flag: "🇰🇿", region: "Asia", description: "منح Bolashak الرئاسية للدراسة في الخارج.", latitude: 48.0196, longitude: 66.9237 },
  { code: "UZ", name: "Uzbekistan", nameAr: "أوزبكستان", flag: "🇺🇿", region: "Asia", description: "فرص دراسية بأسعار منخفضة وثقافة غنية.", latitude: 41.3775, longitude: 64.5853 },
  { code: "TM", name: "Turkmenistan", nameAr: "تركمانستان", flag: "🇹🇲", region: "Asia", description: "فرص دراسية في آسيا الوسطى.", latitude: 38.9697, longitude: 59.5563 },
  { code: "TJ", name: "Tajikistan", nameAr: "طاجيكستان", flag: "🇹🇯", region: "Asia", description: "تعليم بأسعار معقولة في آسيا الوسطى.", latitude: 38.8610, longitude: 71.2761 },
  { code: "KG", name: "Kyrgyzstan", nameAr: "قيرغيزستان", flag: "🇰🇬", region: "Asia", description: "منح للدراسات الطبية بأسعار منخفضة.", latitude: 41.2044, longitude: 74.7661 },
  { code: "TR", name: "Turkey", nameAr: "تركيا", flag: "🇹🇷", region: "Asia", description: "منح تركيا الحكومية وبرامج إقامة استثمارية.", latitude: 38.9637, longitude: 35.2433 },
  { code: "AZ", name: "Azerbaijan", nameAr: "أذربيجان", flag: "🇦🇿", region: "Asia", description: "منح للدراسات النفطية والتقنية.", latitude: 40.1431, longitude: 47.5769 },
  { code: "GE", name: "Georgia", nameAr: "جورجيا", flag: "🇬🇪", region: "Asia", description: "تأشيرات مرنة لسنة كاملة وفرص استثمار.", latitude: 42.3154, longitude: 43.3569 },
  { code: "AM", name: "Armenia", nameAr: "أرمينيا", flag: "🇦🇲", region: "Asia", description: "تأشيرات سهلة وتكلفة معيشة منخفضة.", latitude: 40.0691, longitude: 45.0382 },

  // Middle East
  { code: "AE", name: "United Arab Emirates", nameAr: "الإمارات", flag: "🇦🇪", region: "Middle East", description: "تأشيرة الذهب وفرص عمل في الخليج.", latitude: 23.4241, longitude: 53.8478 },
  { code: "SA", name: "Saudi Arabia", nameAr: "السعودية", flag: "🇸🇦", region: "Middle East", description: "منح خادم الحرمين وفرص في القطاع التعليمي.", latitude: 23.8859, longitude: 45.0792 },
  { code: "QA", name: "Qatar", nameAr: "قطر", flag: "🇶🇦", region: "Middle East", description: "جامعات عالمية وفرص توظيف عالية الراتب.", latitude: 25.3548, longitude: 51.1839 },
  { code: "KW", name: "Kuwait", nameAr: "الكويت", flag: "🇰🇼", region: "Middle East", description: "منح حكومية وفرص دراسية وعمل.", latitude: 29.3117, longitude: 47.4818 },
  { code: "BH", name: "Bahrain", nameAr: "البحرين", flag: "🇧🇭", region: "Middle East", description: "وجهة عمل خليجية وتأشيرة Golden.", latitude: 25.9304, longitude: 50.6378 },
  { code: "OM", name: "Oman", nameAr: "عمان", flag: "🇴🇲", region: "Middle East", description: "فرص عمل وتعليم في السلطنة.", latitude: 21.4735, longitude: 55.9754 },
  { code: "JO", name: "Jordan", nameAr: "الأردن", flag: "🇯🇴", region: "Middle East", description: "جامعات معترف بها وتعليم بأسعار معقولة.", latitude: 30.5852, longitude: 36.2384 },
  { code: "LB", name: "Lebanon", nameAr: "لبنان", flag: "🇱🇧", region: "Middle East", description: "جامعات تاريخية ومنح ثقافية.", latitude: 33.8547, longitude: 35.8623 },
  { code: "IQ", name: "Iraq", nameAr: "العراق", flag: "🇮🇶", region: "Middle East", description: "منح حكومية للدراسات العليا.", latitude: 33.2232, longitude: 43.6793 },
  { code: "SY", name: "Syria", nameAr: "سوريا", flag: "🇸🇾", region: "Middle East", description: "منح حكومية للدراسة باللغة العربية.", latitude: 34.8021, longitude: 38.9968 },
  { code: "YE", name: "Yemen", nameAr: "اليمن", flag: "🇾🇪", region: "Middle East", description: "منح حكومية بأسعار رمزية.", latitude: 15.5527, longitude: 48.5164 },
  { code: "PS", name: "Palestine", nameAr: "فلسطين", flag: "🇵🇸", region: "Middle East", description: "منح للدعم الأكاديمي والثقافي.", latitude: 31.9522, longitude: 35.2332 },
  { code: "IR", name: "Iran", nameAr: "إيران", flag: "🇮🇷", region: "Middle East", description: "منح للدراسات الإسلامية والعلمية.", latitude: 32.4279, longitude: 53.6880 },
  { code: "IL", name: "Israel", nameAr: "إسرائيل", flag: "🇮🇱", region: "Middle East", description: "منح للأبحاث في التكنولوجيا والعلوم.", latitude: 31.0461, longitude: 34.8516 },

  // Africa
  { code: "EG", name: "Egypt", nameAr: "مصر", flag: "🇪🇬", region: "Africa", description: "أكبر مركز تعليمي في الشرق الأوسط ومنح حكومية متعددة.", latitude: 26.8206, longitude: 30.8025 },
  { code: "MA", name: "Morocco", nameAr: "المغرب", flag: "🇲🇦", region: "Africa", description: "جامعات فرنسية وعربية ومنح للتبادل الأفريقي.", latitude: 31.7917, longitude: -7.0926 },
  { code: "DZ", name: "Algeria", nameAr: "الجزائر", flag: "🇩🇿", region: "Africa", description: "تعليم مجاني وفرص للطلاب الأفارقة.", latitude: 28.0339, longitude: 1.6596 },
  { code: "TN", name: "Tunisia", nameAr: "تونس", flag: "🇹🇳", region: "Africa", description: "تعليم باللغة الفرنسية والعربية وفرص تبادل.", latitude: 33.8869, longitude: 9.5375 },
  { code: "LY", name: "Libya", nameAr: "ليبيا", flag: "🇱🇾", region: "Africa", description: "منح حكومية للدراسة المحلية.", latitude: 26.3351, longitude: 17.2283 },
  { code: "SD", name: "Sudan", nameAr: "السودان", flag: "🇸🇩", region: "Africa", description: "منح حكومية للدراسات الشرقية والعربية.", latitude: 12.8628, longitude: 30.2176 },
  { code: "ET", name: "Ethiopia", nameAr: "إثيوبيا", flag: "🇪🇹", region: "Africa", description: "وجهة للمنظمات الدولية والدراسات الأفريقية.", latitude: 9.1450, longitude: 40.4897 },
  { code: "KE", name: "Kenya", nameAr: "كينيا", flag: "🇰🇪", region: "Africa", description: "منح للدراسات البيئية والطبية.", latitude: -0.0236, longitude: 37.9062 },
  { code: "TZ", name: "Tanzania", nameAr: "تنزانيا", flag: "🇹🇿", region: "Africa", description: "وجهة للأبحاث الحيوانية والبيئية.", latitude: -6.3690, longitude: 34.8888 },
  { code: "UG", name: "Uganda", nameAr: "أوغندا", flag: "🇺🇬", region: "Africa", description: "فرص دراسية وأبحاث في أفريقيا الشرقية.", latitude: 1.3733, longitude: 32.2903 },
  { code: "RW", name: "Rwanda", nameAr: "رواندا", flag: "🇷🇼", region: "Africa", description: "اقتصاد صاعد وفرص استثمار في التكنولوجيا.", latitude: -1.9403, longitude: 29.8739 },
  { code: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا", flag: "🇿🇦", region: "Africa", description: "أكبر اقتصاد أفريقي وجامعات بحثية رائدة.", latitude: -30.5595, longitude: 22.9375 },
  { code: "NG", name: "Nigeria", nameAr: "نيجيريا", flag: "🇳🇬", region: "Africa", description: "أكبر سوق عمل في غرب أفريقيا.", latitude: 9.0820, longitude: 8.6753 },
  { code: "GH", name: "Ghana", nameAr: "غانا", flag: "🇬🇭", region: "Africa", description: "وجهة مستقرة للدراسة باللغة الإنجليزية.", latitude: 7.9465, longitude: -1.0232 },
  { code: "SN", name: "Senegal", nameAr: "السنغال", flag: "🇸🇳", region: "Africa", description: "منح للدراسات الفرانكوفونية والإسلامية.", latitude: 14.4974, longitude: -14.4524 },
  { code: "CI", name: "Ivory Coast", nameAr: "ساحل العاج", flag: "🇨🇮", region: "Africa", description: "أكبر اقتصاد فرانكوفوني في غرب أفريقيا.", latitude: 7.5400, longitude: -5.5471 },
  { code: "CM", name: "Cameroon", nameAr: "الكاميرون", flag: "🇨🇲", region: "Africa", description: "تعليم ثنائي اللغة وفرص بحثية.", latitude: 7.3697, longitude: 12.3547 },
  { code: "ML", name: "Mali", nameAr: "مالي", flag: "🇲🇱", region: "Africa", description: "منح للدراسات الإسلامية والأفريقية.", latitude: 17.5707, longitude: -3.9962 },
  { code: "BF", name: "Burkina Faso", nameAr: "بوركينا فاسو", flag: "🇧🇫", region: "Africa", description: "منح للدراسات الأفريقية.", latitude: 12.2383, longitude: -1.5616 },
  { code: "NE", name: "Niger", nameAr: "النيجر", flag: "🇳🇪", region: "Africa", description: "وجهة للدراسات الزراعية والبيئية.", latitude: 17.6078, longitude: 8.0817 },
  { code: "TD", name: "Chad", nameAr: "تشاد", flag: "🇹🇩", region: "Africa", description: "فرص بحثية في وسط أفريقيا.", latitude: 15.4542, longitude: 18.7322 },
  { code: "MR", name: "Mauritania", nameAr: "موريتانيا", flag: "🇲🇷", region: "Africa", description: "منح للدراسات الإسلامية والصحراوية.", latitude: 21.0079, longitude: -10.9408 },
  { code: "SO", name: "Somalia", nameAr: "الصومال", flag: "🇸🇴", region: "Africa", description: "فرص للأبحاث في القرن الأفريقي.", latitude: 5.1521, longitude: 46.1996 },
  { code: "DJ", name: "Djibouti", nameAr: "جيبوتي", flag: "🇩🇯", region: "Africa", description: "موقع استراتيجي وفرص في الخدمات اللوجستية.", latitude: 11.8251, longitude: 42.5903 },
  { code: "ER", name: "Eritrea", nameAr: "إريتريا", flag: "🇪🇷", region: "Africa", description: "فرص دراسية في القرن الأفريقي.", latitude: 15.1794, longitude: 39.7823 },
  { code: "AO", name: "Angola", nameAr: "أنغولا", flag: "🇦🇴", region: "Africa", description: "اقتصاد نفطي وفرص في القطاع الطاقي.", latitude: -11.2027, longitude: 17.8739 },
  { code: "MZ", name: "Mozambique", nameAr: "موزمبيق", flag: "🇲🇿", region: "Africa", description: "وجهة للأبحاث البحرية والبيئية.", latitude: -18.6657, longitude: 35.5296 },
  { code: "ZW", name: "Zimbabwe", nameAr: "زيمبابوي", flag: "🇿🇼", region: "Africa", description: "تعليم باللغة الإنجليزية بأسعار معقولة.", latitude: -19.0154, longitude: 29.1549 },
  { code: "ZM", name: "Zambia", nameAr: "زامبيا", flag: "🇿🇲", region: "Africa", description: "فرص بحثية في الجيولوجيا والمناجم.", latitude: -13.1339, longitude: 27.8493 },
  { code: "BW", name: "Botswana", nameAr: "بوتسوانا", flag: "🇧🇼", region: "Africa", description: "أحد أكثر الدول استقراراً في أفريقيا.", latitude: -22.3285, longitude: 24.6849 },
  { code: "NA", name: "Namibia", nameAr: "ناميبيا", flag: "🇳🇦", region: "Africa", description: "فرص للأبحاث الصحراوية والبيئية.", latitude: -22.9576, longitude: 18.4904 },
  { code: "MG", name: "Madagascar", nameAr: "مدغشقر", flag: "🇲🇬", region: "Africa", description: "وجهة فريدة للأبحاث البيولوجية.", latitude: -18.7669, longitude: 46.8691 },
  { code: "MU", name: "Mauritius", nameAr: "موريشيوس", flag: "🇲🇺", region: "Africa", description: "وجهة سياحية وفرص استثمار في القطاع المصرفي.", latitude: -20.3484, longitude: 57.5522 },
  { code: "SC", name: "Seychelles", nameAr: "سيشل", flag: "🇸🇨", region: "Africa", description: "منح للدراسات البحرية والسياحة.", latitude: -4.6796, longitude: 55.4920 },
  { code: "CV", name: "Cape Verde", nameAr: "الرأس الأخضر", flag: "🇨🇻", region: "Africa", description: "تأشيرات استثمار سهلة وجزر آمنة.", latitude: 16.5388, longitude: -23.0418 },
  { code: "GM", name: "Gambia", nameAr: "غامبيا", flag: "🇬🇲", region: "Africa", description: "وجهة للدراسات الأفريقية باللغة الإنجليزية.", latitude: 13.4432, longitude: -15.3101 },
  { code: "GN", name: "Guinea", nameAr: "غينيا", flag: "🇬🇳", region: "Africa", description: "فرص بحثية في غرب أفريقيا.", latitude: 9.9456, longitude: -9.6966 },
  { code: "SL", name: "Sierra Leone", nameAr: "سيراليون", flag: "🇸🇱", region: "Africa", description: "تعليم باللغة الإنجليزية في غرب أفريقيا.", latitude: 8.4606, longitude: -11.7799 },
  { code: "LR", name: "Liberia", nameAr: "ليبيريا", flag: "🇱🇷", region: "Africa", description: "تعليم باللغة الإنجليزية في غرب أفريقيا.", latitude: 6.4281, longitude: -9.4295 },
  { code: "TG", name: "Togo", nameAr: "توغو", flag: "🇹🇬", region: "Africa", description: "فرص بحثية في غرب أفريقيا.", latitude: 8.6195, longitude: 0.8248 },
  { code: "BJ", name: "Benin", nameAr: "بنين", flag: "🇧🇯", region: "Africa", description: "تعليم باللغة الفرنسية في غرب أفريقيا.", latitude: 9.3077, longitude: 2.3158 },
  { code: "GA", name: "Gabon", nameAr: "الغابون", flag: "🇬🇦", region: "Africa", description: "أبحاث في الغابات الاستوائية.", latitude: -0.8037, longitude: 11.6094 },
  { code: "CG", name: "Republic of Congo", nameAr: "جمهورية الكونغو", flag: "🇨🇬", region: "Africa", description: "فرص بحثية في وسط أفريقيا.", latitude: -0.2280, longitude: 15.8277 },
  { code: "CD", name: "DR Congo", nameAr: "الكونغو الديمقراطية", flag: "🇨🇩", region: "Africa", description: "أبحاث في التنوع الحيوي.", latitude: -4.0383, longitude: 21.7587 },
  { code: "CF", name: "Central African Republic", nameAr: "أفريقيا الوسطى", flag: "🇨🇫", region: "Africa", description: "فرص بحثية في وسط أفريقيا.", latitude: 6.6111, longitude: 20.9394 },
  { code: "BI", name: "Burundi", nameAr: "بوروندي", flag: "🇧🇮", region: "Africa", description: "وجهة للدراسات الأفريقية.", latitude: -3.3731, longitude: 29.9189 },
  { code: "MW", name: "Malawi", nameAr: "ملاوي", flag: "🇲🇼", region: "Africa", description: "فرص بحثية في البحيرات والبيئة.", latitude: -13.2543, longitude: 34.3015 },
  { code: "LS", name: "Lesotho", nameAr: "ليسوتو", flag: "🇱🇸", region: "Africa", description: "وجهة جبلية للأبحاث المناخية.", latitude: -29.6100, longitude: 28.2336 },
  { code: "SZ", name: "Eswatini", nameAr: "إسواتيني", flag: "🇸🇿", region: "Africa", description: "فرص دراسية في الجنوب الأفريقي.", latitude: -26.5225, longitude: 31.4659 },
  { code: "SS", name: "South Sudan", nameAr: "جنوب السودان", flag: "🇸🇸", region: "Africa", description: "فرص للعمل الإنساني والتنموي.", latitude: 6.8770, longitude: 31.3070 },
  { code: "GQ", name: "Equatorial Guinea", nameAr: "غينيا الاستوائية", flag: "🇬🇶", region: "Africa", description: "اقتصاد نفطي صغير في وسط أفريقيا.", latitude: 1.6508, longitude: 10.2679 },
  { code: "ST", name: "São Tomé and Príncipe", nameAr: "ساو تومي وبرنسيب", flag: "🇸🇹", region: "Africa", description: "جزر صغيرة بفرص للسياحة البيئية.", latitude: 0.1864, longitude: 6.6131 },
  { code: "KM", name: "Comoros", nameAr: "جزر القمر", flag: "🇰🇲", region: "Africa", description: "وجهة للدراسات الإسلامية في المحيط الهندي.", latitude: -11.6455, longitude: 43.3333 },

  // Oceania
  { code: "AU", name: "Australia", nameAr: "أستراليا", flag: "🇦🇺", region: "Oceania", description: "وجهة هجرة رائدة عبر Skilled Migration وSubclass 482.", latitude: -25.2744, longitude: 133.7751 },
  { code: "NZ", name: "New Zealand", nameAr: "نيوزيلندا", flag: "🇳🇿", region: "Oceania", description: "تأشيرات Skilled Migrant وفرص للعمل والإقامة.", latitude: -40.9006, longitude: 174.8860 },
  { code: "FJ", name: "Fiji", nameAr: "فيجي", flag: "🇫🇯", region: "Oceania", description: "وجهة سياحية وفرص في القطاع الفندقي.", latitude: -16.5784, longitude: 179.4144 },
  { code: "PG", name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", flag: "🇵🇬", region: "Oceania", description: "فرص بحثية في التنوع البيولوجي.", latitude: -6.3149, longitude: 143.9555 },
  { code: "VU", name: "Vanuatu", nameAr: "فانواتو", flag: "🇻🇺", region: "Oceania", description: "تأشيرة استثمار للحصول على الجنسية.", latitude: -15.3767, longitude: 166.9592 },
  { code: "SB", name: "Solomon Islands", nameAr: "جزر سليمان", flag: "🇸🇧", region: "Oceania", description: "وجهة للدراسات البحرية.", latitude: -9.6457, longitude: 160.1562 },
  { code: "WS", name: "Samoa", nameAr: "ساموا", flag: "🇼🇸", region: "Oceania", description: "ثقافة بولينيزية أصيلة وفرص بحثية.", latitude: -13.7590, longitude: -172.1046 },
  { code: "TO", name: "Tonga", nameAr: "تونغا", flag: "🇹🇴", region: "Oceania", description: "مملكة بولينيزية وفرص للبحث الثقافي.", latitude: -21.1789, longitude: -175.1982 },
  { code: "MH", name: "Marshall Islands", nameAr: "جزر مارشال", flag: "🇲🇭", region: "Oceania", description: "أبحاث المحيطات والمناخ.", latitude: 7.1315, longitude: 171.1845 },

  // Additional Asia
  { code: "BN", name: "Brunei", nameAr: "بروناي", flag: "🇧🇳", region: "Asia", description: "منح حكومية للدراسات الإسلامية.", latitude: 4.5353, longitude: 114.7277 },
  { code: "TL", name: "Timor-Leste", nameAr: "تيمور الشرقية", flag: "🇹🇱", region: "Asia", description: "دولة ناشئة بفرص تنموية.", latitude: -8.8742, longitude: 125.7275 },
  { code: "MV", name: "Maldives", nameAr: "المالديف", flag: "🇲🇻", region: "Asia", description: "فرص بحثية في علوم البحار وتغير المناخ.", latitude: 3.2028, longitude: 73.2207 },
  { code: "BT", name: "Bhutan", nameAr: "بوتان", flag: "🇧🇹", region: "Asia", description: "مملكة هيمالايا فريدة بفرص بحثية.", latitude: 27.5142, longitude: 90.4336 },
  { code: "AF", name: "Afghanistan", nameAr: "أفغانستان", flag: "🇦🇫", region: "Asia", description: "منح للدراسات الإسلامية والإنسانية.", latitude: 33.9391, longitude: 67.7100 },
  { code: "TW", name: "Taiwan", nameAr: "تايوان", flag: "🇹🇼", region: "Asia", description: "منح Taiwan Scholarship وتعليم تكنولوجي رائد.", latitude: 23.6978, longitude: 120.9605 },
  { code: "HK", name: "Hong Kong", nameAr: "هونغ كونغ", flag: "🇭🇰", region: "Asia", description: "جامعات عالمية وفرص في القطاع المالي.", latitude: 22.3193, longitude: 114.1694 },
  { code: "MO", name: "Macau", nameAr: "ماكاو", flag: "🇲🇴", region: "Asia", description: "فرص دراسية في القطاع السياحي.", latitude: 22.1987, longitude: 113.5439 },

  // Russia & CIS
  { code: "RU", name: "Russia", nameAr: "روسيا", flag: "🇷🇺", region: "Europe", description: "منح Open Doors وفرص دراسية في الطب والهندسة.", latitude: 61.5240, longitude: 105.3188 },
  { code: "BY", name: "Belarus", nameAr: "بيلاروسيا", flag: "🇧🇾", region: "Europe", description: "تعليم تقني بأسعار منخفضة.", latitude: 53.7098, longitude: 27.9534 },
  { code: "UA", name: "Ukraine", nameAr: "أوكرانيا", flag: "🇺🇦", region: "Europe", description: "تعليم طبي بأسعار معقولة.", latitude: 48.3794, longitude: 31.1656 },
  { code: "MD", name: "Moldova", nameAr: "مولدوفا", flag: "🇲🇩", region: "Europe", description: "تعليم بأسعار منخفضة في أوروبا الشرقية.", latitude: 47.4116, longitude: 28.3699 },
  { code: "AL", name: "Albania", nameAr: "ألبانيا", flag: "🇦🇱", region: "Europe", description: "وجهة ناشئة في البلقان.", latitude: 41.1533, longitude: 20.1683 },
  { code: "MK", name: "North Macedonia", nameAr: "مقدونيا الشمالية", flag: "🇲🇰", region: "Europe", description: "فرص دراسية في البلقان.", latitude: 41.6086, longitude: 21.7453 },
  { code: "BA", name: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك", flag: "🇧🇦", region: "Europe", description: "وجهة دراسية بأسعار معقولة.", latitude: 43.9159, longitude: 17.6791 },
  { code: "ME", name: "Montenegro", nameAr: "الجبل الأسود", flag: "🇲🇪", region: "Europe", description: "تأشيرات استثمار وإقامة.", latitude: 42.7087, longitude: 19.3744 },
  { code: "XK", name: "Kosovo", nameAr: "كوسوفو", flag: "🇽🇰", region: "Europe", description: "بلد جديد بفرص نمو وتنمية.", latitude: 42.6026, longitude: 20.9030 },

  // Caribbean / micro
  { code: "BZ", name: "Belize", nameAr: "بليز", flag: "🇧🇿", region: "North America", description: "تعليم باللغة الإنجليزية في أمريكا الوسطى.", latitude: 17.1899, longitude: -88.4976 },
  { code: "BS", name: "Bahamas", nameAr: "البهاما", flag: "🇧🇸", region: "North America", description: "وجهة سياحية وفرص في القطاع المصرفي.", latitude: 25.0343, longitude: -77.3963 },
  { code: "BB", name: "Barbados", nameAr: "بربادوس", flag: "🇧🇧", region: "North America", description: "تأشيرات للرحالة الرقميين.", latitude: 13.1939, longitude: -59.5432 },
  { code: "TT", name: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو", flag: "🇹🇹", region: "North America", description: "تعليم باللغة الإنجليزية في الكاريبي.", latitude: 10.6918, longitude: -61.2225 },
  { code: "AG", name: "Antigua and Barbuda", nameAr: "أنتيغوا وبربودا", flag: "🇦🇬", region: "North America", description: "تأشيرات استثمار للحصول على الجنسية.", latitude: 17.0608, longitude: -61.7964 },
  { code: "DM", name: "Dominica", nameAr: "دومينيكا", flag: "🇩🇲", region: "North America", description: "برنامج جنسية مقابل الاستثمار.", latitude: 15.4150, longitude: -61.3710 },
  { code: "GD", name: "Grenada", nameAr: "غرينادا", flag: "🇬🇩", region: "North America", description: "برنامج جنسية بالاستثمار وكلية طب St George's.", latitude: 12.1165, longitude: -61.6790 },
  { code: "LC", name: "Saint Lucia", nameAr: "سانت لوسيا", flag: "🇱🇨", region: "North America", description: "برنامج جنسية بالاستثمار.", latitude: 13.9094, longitude: -60.9789 },
  { code: "KN", name: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس", flag: "🇰🇳", region: "North America", description: "أقدم برنامج جنسية بالاستثمار في العالم.", latitude: 17.3578, longitude: -62.7830 },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameAr: "سانت فنسنت والغرينادين", flag: "🇻🇨", region: "North America", description: "وجهة سياحية كاريبية.", latitude: 12.9843, longitude: -61.2872 },
  { code: "GY", name: "Guyana", nameAr: "غيانا", flag: "🇬🇾", region: "South America", description: "تعليم باللغة الإنجليزية في أمريكا الجنوبية.", latitude: 4.8604, longitude: -58.9302 },
  { code: "SR", name: "Suriname", nameAr: "سورينام", flag: "🇸🇷", region: "South America", description: "وجهة فريدة بثقافة هولندية وآسيوية.", latitude: 3.9193, longitude: -56.0278 },
  { code: "AD", name: "Andorra", nameAr: "أندورا", flag: "🇦🇩", region: "Europe", description: "إقامة ضريبية ميسرة.", latitude: 42.5063, longitude: 1.5218 },
  { code: "MC", name: "Monaco", nameAr: "موناكو", flag: "🇲🇨", region: "Europe", description: "إقامة فاخرة على الريفييرا.", latitude: 43.7384, longitude: 7.4246 },
  { code: "SM", name: "San Marino", nameAr: "سان مارينو", flag: "🇸🇲", region: "Europe", description: "أقدم جمهورية في العالم.", latitude: 43.9424, longitude: 12.4578 },
  { code: "VA", name: "Vatican City", nameAr: "الفاتيكان", flag: "🇻🇦", region: "Europe", description: "مركز ديني وثقافي للأبحاث الدينية.", latitude: 41.9029, longitude: 12.4534 },
  { code: "LI", name: "Liechtenstein", nameAr: "ليختنشتاين", flag: "🇱🇮", region: "Europe", description: "إمارة صغيرة بفرص في القطاع المالي.", latitude: 47.1660, longitude: 9.5554 },
];
