import type { InsertCountry, InsertOpportunity } from "@workspace/db";

// Templates for scholarships per region; each becomes 6-12 opportunities per country
type ScholarshipTemplate = {
  titleAr: (countryAr: string) => string;
  title: (country: string) => string;
  organization: (country: string) => string;
  degreeLevel: string;
  field: string;
  funding: string;
  amount: string;
  duration: string;
  benefits: string[];
  requirements: string[];
  tags: string[];
  description: (countryAr: string) => string;
  eligibility: string;
  acceptanceRate: number;
  difficulty: number;
  type: "scholarship";
};

type MigrationTemplate = {
  titleAr: (countryAr: string) => string;
  title: (country: string) => string;
  organization: (country: string) => string;
  degreeLevel: string;
  field: string;
  funding: string;
  amount: string;
  duration: string;
  benefits: string[];
  requirements: string[];
  tags: string[];
  description: (countryAr: string) => string;
  eligibility: string;
  acceptanceRate: number;
  difficulty: number;
  type: "migration";
};

type Template = ScholarshipTemplate | MigrationTemplate;

const SCHOLARSHIP_TEMPLATES: ScholarshipTemplate[] = [
  {
    type: "scholarship",
    titleAr: (c) => `منحة الحكومة لدراسة البكالوريوس في ${c}`,
    title: (c) => `Government Bachelor Scholarship in ${c}`,
    organization: (c) => `Ministry of Higher Education - ${c}`,
    degreeLevel: "Bachelor",
    field: "All Fields",
    funding: "Full Funding",
    amount: "تغطية كاملة + بدل شهري",
    duration: "4 سنوات",
    benefits: ["رسوم دراسية كاملة", "بدل معيشة شهري", "تأمين صحي", "تذكرة طيران سنوية"],
    requirements: ["شهادة الثانوية العامة بمعدل 85%+", "إتقان اللغة (IELTS 6.0 أو ما يعادلها)", "خطاب توصية", "السيرة الذاتية"],
    tags: ["بكالوريوس", "تمويل كامل", "حكومية"],
    description: (c) => `منحة حكومية مرموقة في ${c} مفتوحة للطلاب الدوليين لدراسة البكالوريوس في تخصصات متعددة، تغطي الرسوم وبدل المعيشة.`,
    eligibility: "الطلاب الدوليون من جميع الدول، الحاصلون على الثانوية بمعدل عالٍ.",
    acceptanceRate: 18,
    difficulty: 4,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة الماجستير الحكومية في ${c}`,
    title: (c) => `Master's Government Scholarship in ${c}`,
    organization: (c) => `Higher Education Council - ${c}`,
    degreeLevel: "Master",
    field: "Engineering & Sciences",
    funding: "Full Funding",
    amount: "تغطية كاملة + 1500$ شهرياً",
    duration: "سنتان",
    benefits: ["رسوم دراسية كاملة", "بدل شهري ممتاز", "تأمين صحي شامل", "تكاليف الأبحاث"],
    requirements: ["بكالوريوس بمعدل 75%+", "إتقان اللغة الإنجليزية (IELTS 6.5)", "خطابات توصية", "خطاب الدوافع", "سيرة ذاتية أكاديمية"],
    tags: ["ماجستير", "تمويل كامل", "هندسة", "علوم"],
    description: (c) => `برنامج منح للماجستير في ${c} يستهدف المتفوقين في الهندسة والعلوم، يقدم تمويلاً كاملاً ودعماً بحثياً.`,
    eligibility: "خريجو البكالوريوس بمعدل 75% فما فوق في الهندسة أو العلوم الطبيعية.",
    acceptanceRate: 15,
    difficulty: 4,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة الدكتوراه البحثية في ${c}`,
    title: (c) => `Doctoral Research Scholarship in ${c}`,
    organization: (c) => `Research Foundation of ${c}`,
    degreeLevel: "PhD",
    field: "Research",
    funding: "Full Funding",
    amount: "ممولة بالكامل + راتب شهري",
    duration: "3-4 سنوات",
    benefits: ["راتب شهري للباحث", "رسوم دراسية", "ميزانية للمؤتمرات", "دعم النشر العلمي"],
    requirements: ["ماجستير بتقدير ممتاز", "نشرات علمية مفضلة", "مقترح بحثي", "مشرف من الجامعة"],
    tags: ["دكتوراه", "بحث علمي", "تمويل كامل"],
    description: (c) => `فرصة للحصول على درجة الدكتوراه في ${c} ضمن مجموعات بحثية رائدة، مع تمويل كامل ومنحة شهرية محترمة.`,
    eligibility: "حاملو الماجستير بنتائج ممتازة، مع خبرة بحثية أو نشرات علمية.",
    acceptanceRate: 10,
    difficulty: 5,
  },
  {
    type: "scholarship",
    titleAr: (c) => `برنامج تبادل طلابي في ${c}`,
    title: (c) => `Student Exchange Program in ${c}`,
    organization: (c) => `International Office - ${c}`,
    degreeLevel: "Bachelor / Master",
    field: "All Fields",
    funding: "Partial",
    amount: "إعفاء من الرسوم + 800$ شهرياً",
    duration: "فصل دراسي إلى سنة",
    benefits: ["إعفاء من الرسوم", "بدل معيشة", "تأمين صحي"],
    requirements: ["تسجيل حالي في جامعة", "معدل أكاديمي جيد", "إتقان اللغة"],
    tags: ["تبادل طلابي", "قصير الأمد"],
    description: (c) => `برنامج تبادل طلابي إلى ${c} يتيح للطلاب قضاء فصل أو سنة في جامعات شريكة مع تمويل جزئي.`,
    eligibility: "الطلاب المسجلون حالياً في جامعات معتمدة.",
    acceptanceRate: 30,
    difficulty: 3,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة دراسة الطب في ${c}`,
    title: (c) => `Medical Studies Scholarship in ${c}`,
    organization: (c) => `Medical Council of ${c}`,
    degreeLevel: "Bachelor / Master",
    field: "Medicine",
    funding: "Partial",
    amount: "خصم 60% من الرسوم",
    duration: "5-6 سنوات",
    benefits: ["خصم 60% من الرسوم", "إقامة جامعية", "تدريب سريري"],
    requirements: ["شهادة ثانوية علمية بمعدل 90%+", "اختبار قبول", "اختبار اللغة"],
    tags: ["طب", "صحة", "خصم رسوم"],
    description: (c) => `فرصة دراسة الطب في كليات معترف بها في ${c} مع خصم كبير على الرسوم وتدريب سريري متميز.`,
    eligibility: "خريجو الثانوية العلمية بمعدل عالٍ ومتفوقون في المواد العلمية.",
    acceptanceRate: 12,
    difficulty: 5,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة دراسة الهندسة في ${c}`,
    title: (c) => `Engineering Scholarship in ${c}`,
    organization: (c) => `Engineering Universities of ${c}`,
    degreeLevel: "Bachelor",
    field: "Engineering",
    funding: "Partial",
    amount: "خصم 40-70% من الرسوم",
    duration: "4 سنوات",
    benefits: ["خصم على الرسوم", "تدريب صناعي", "دعم البحث"],
    requirements: ["ثانوية علمية بمعدل 80%+", "اختبار رياضيات", "إتقان اللغة الإنجليزية"],
    tags: ["هندسة", "تكنولوجيا", "بكالوريوس"],
    description: (c) => `منح لدراسة الهندسة في كليات ${c} مع خصم على الرسوم وفرص تدريب صناعي.`,
    eligibility: "خريجو الثانوية العلمية المتفوقون في الرياضيات والفيزياء.",
    acceptanceRate: 25,
    difficulty: 3,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة إدارة الأعمال (MBA) في ${c}`,
    title: (c) => `MBA Scholarship in ${c}`,
    organization: (c) => `Business Schools Network - ${c}`,
    degreeLevel: "Master",
    field: "Business",
    funding: "Partial",
    amount: "30-50% من الرسوم",
    duration: "1-2 سنة",
    benefits: ["خصم رسوم", "ورش عمل احترافية", "تواصل مع شركات عالمية"],
    requirements: ["بكالوريوس", "خبرة عملية 2-3 سنوات", "GMAT أو ما يعادله", "خطاب الدوافع"],
    tags: ["MBA", "إدارة أعمال", "ماجستير"],
    description: (c) => `منحة لدراسة الماجستير في إدارة الأعمال (MBA) في كليات ${c} المعتمدة دولياً.`,
    eligibility: "العاملون في القطاع الإداري مع خبرة لا تقل عن سنتين.",
    acceptanceRate: 20,
    difficulty: 4,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة دراسات الفنون والإنسانيات في ${c}`,
    title: (c) => `Arts & Humanities Scholarship in ${c}`,
    organization: (c) => `Cultural Foundation of ${c}`,
    degreeLevel: "Bachelor / Master",
    field: "Arts & Humanities",
    funding: "Partial",
    amount: "إعفاء جزئي + 500$ شهرياً",
    duration: "2-4 سنوات",
    benefits: ["إعفاء جزئي", "بدل بسيط للمعيشة", "ورش فنية"],
    requirements: ["شهادة سابقة", "بورتفوليو فني (للفنون)", "اختبار اللغة"],
    tags: ["فنون", "إنسانيات", "ثقافة"],
    description: (c) => `منحة لدارسي الفنون والآداب والإنسانيات في ${c} مع دعم جزئي وفرص للمشاركة في فعاليات ثقافية.`,
    eligibility: "الطلاب المهتمون بالفنون والآداب والعلوم الإنسانية.",
    acceptanceRate: 28,
    difficulty: 3,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة دراسة تكنولوجيا المعلومات في ${c}`,
    title: (c) => `IT & Computer Science Scholarship in ${c}`,
    organization: (c) => `Tech Universities Consortium - ${c}`,
    degreeLevel: "Bachelor / Master",
    field: "Computer Science",
    funding: "Partial",
    amount: "خصم 50% + بدل سكن",
    duration: "2-4 سنوات",
    benefits: ["خصم رسوم", "بدل سكن", "تدريب في شركات تقنية"],
    requirements: ["ثانوية بمعدل 80%+ أو بكالوريوس", "اختبار البرمجة", "إتقان الإنجليزية"],
    tags: ["برمجة", "تكنولوجيا", "ذكاء اصطناعي"],
    description: (c) => `منحة دراسة علوم الحاسب وتكنولوجيا المعلومات في ${c} مع تدريب عملي في شركات رائدة.`,
    eligibility: "الطلاب المتفوقون في الرياضيات والعلوم والمهتمون بالبرمجة.",
    acceptanceRate: 22,
    difficulty: 4,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة الدراسات البيئية في ${c}`,
    title: (c) => `Environmental Studies Scholarship in ${c}`,
    organization: (c) => `Environmental Council - ${c}`,
    degreeLevel: "Master / PhD",
    field: "Environmental Science",
    funding: "Full Funding",
    amount: "ممولة بالكامل",
    duration: "2-4 سنوات",
    benefits: ["تمويل كامل", "ميدان أبحاث متاح", "دعم المؤتمرات"],
    requirements: ["شهادة جامعية في علوم ذات صلة", "خبرة بحثية مفضلة", "خطة بحث"],
    tags: ["بيئة", "استدامة", "أبحاث"],
    description: (c) => `منحة بحثية في مجال البيئة والاستدامة في ${c}، تستهدف الباحثين في تغير المناخ والطاقة المتجددة.`,
    eligibility: "خريجو علوم بيئية أو تخصصات ذات صلة.",
    acceptanceRate: 20,
    difficulty: 4,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة دراسة اللغة في ${c}`,
    title: (c) => `Language Program Scholarship in ${c}`,
    organization: (c) => `Language Institute of ${c}`,
    degreeLevel: "Diploma",
    field: "Language Studies",
    funding: "Partial",
    amount: "إعفاء كامل من الرسوم",
    duration: "3-12 شهراً",
    benefits: ["إعفاء من رسوم اللغة", "تأمين صحي", "تذكرة طيران لبعض البرامج"],
    requirements: ["شهادة جامعية أو طالب جامعي", "خطاب دوافع", "اختبار مستوى اللغة"],
    tags: ["لغة", "ثقافة", "قصير الأمد"],
    description: (c) => `برنامج منحة لتعلم اللغة المحلية في ${c}، مدعوم من المراكز الثقافية الرسمية.`,
    eligibility: "طلاب جامعيون أو خريجون مهتمون بتعلم اللغة المحلية.",
    acceptanceRate: 35,
    difficulty: 2,
  },
  {
    type: "scholarship",
    titleAr: (c) => `منحة الزراعة والأمن الغذائي في ${c}`,
    title: (c) => `Agriculture & Food Security Scholarship in ${c}`,
    organization: (c) => `Agricultural Research Institute - ${c}`,
    degreeLevel: "Master",
    field: "Agriculture",
    funding: "Full Funding",
    amount: "تمويل كامل",
    duration: "سنتان",
    benefits: ["تمويل كامل", "تدريب ميداني", "بدل بحوث"],
    requirements: ["بكالوريوس في الزراعة أو علوم البيئة", "خبرة عملية مفضلة"],
    tags: ["زراعة", "أمن غذائي", "تنمية مستدامة"],
    description: (c) => `منحة متخصصة في الزراعة المستدامة والأمن الغذائي في ${c}، تستهدف خريجي العلوم الزراعية.`,
    eligibility: "خريجو الزراعة والعلوم البيئية ذوو الاهتمام بالتنمية الريفية.",
    acceptanceRate: 24,
    difficulty: 3,
  },
];

const MIGRATION_TEMPLATES: MigrationTemplate[] = [
  {
    type: "migration",
    titleAr: (c) => `تأشيرة العمل الماهر إلى ${c}`,
    title: (c) => `Skilled Worker Visa to ${c}`,
    organization: (c) => `Immigration Department - ${c}`,
    degreeLevel: "Bachelor or higher",
    field: "Skilled Professions",
    funding: "Self-Funded",
    amount: "غير ممول",
    duration: "إقامة 2-5 سنوات قابلة للتجديد",
    benefits: ["إقامة قانونية", "إمكانية الحصول على الإقامة الدائمة", "إحضار العائلة", "وصول لخدمات صحية"],
    requirements: ["عقد عمل من جهة معتمدة", "شهادة جامعية أو خبرة معادلة", "اختبار لغة (إن طُلب)", "السجل الجنائي خالٍ"],
    tags: ["عمل", "إقامة", "مهارات"],
    description: (c) => `برنامج تأشيرة عمل للعمالة الماهرة في ${c} يتيح الحصول على إقامة طويلة الأمد عبر عرض عمل من صاحب عمل معتمد.`,
    eligibility: "أصحاب المهارات المطلوبة في القطاعات ذات الطلب: تكنولوجيا، صحة، هندسة، تعليم.",
    acceptanceRate: 35,
    difficulty: 3,
  },
  {
    type: "migration",
    titleAr: (c) => `الإقامة الدائمة عبر النقاط في ${c}`,
    title: (c) => `Points-Based Permanent Residency in ${c}`,
    organization: (c) => `Immigration & Citizenship - ${c}`,
    degreeLevel: "Bachelor or higher",
    field: "Skilled Migration",
    funding: "Self-Funded",
    amount: "غير ممول",
    duration: "إقامة دائمة",
    benefits: ["إقامة دائمة", "حق العمل لأي صاحب عمل", "حق الالتحاق بالخدمات العامة", "مسار للجنسية"],
    requirements: ["جمع نقاط حسب التعليم والخبرة والعمر واللغة", "تقييم مهني لشهاداتك", "اختبار اللغة", "كشف طبي وجنائي"],
    tags: ["إقامة دائمة", "نقاط", "مهارات"],
    description: (c) => `نظام هجرة قائم على النقاط في ${c} يسمح بالحصول على الإقامة الدائمة بناءً على المؤهلات الشخصية بدون الحاجة لعقد عمل.`,
    eligibility: "العمر بين 18-45، تعليم جامعي، خبرة عملية، إتقان اللغة الإنجليزية أو الفرنسية.",
    acceptanceRate: 28,
    difficulty: 4,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة الرحالة الرقميين في ${c}`,
    title: (c) => `Digital Nomad Visa to ${c}`,
    organization: (c) => `Tourism & Immigration - ${c}`,
    degreeLevel: "Not required",
    field: "Remote Work",
    funding: "Self-Funded",
    amount: "غير ممول",
    duration: "1-2 سنة قابلة للتجديد",
    benefits: ["إقامة قانونية", "العمل عن بعد لشركات أجنبية", "إمكانية إحضار العائلة", "إعفاءات ضريبية في بعض الحالات"],
    requirements: ["دخل شهري مثبت (2500-3500$ شهرياً)", "تأمين صحي دولي", "عقد عمل عن بعد أو نشاط حر", "جواز سفر صالح"],
    tags: ["عمل عن بعد", "رحالة رقمي", "إقامة قصيرة"],
    description: (c) => `تأشيرة مخصصة للعاملين عن بعد للإقامة في ${c} مع الاستمرار في العمل لشركات خارج البلد، مع مزايا ضريبية.`,
    eligibility: "العاملون عن بعد، المستقلون، رواد الأعمال الرقميون بدخل شهري ثابت.",
    acceptanceRate: 60,
    difficulty: 2,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة المستثمر إلى ${c}`,
    title: (c) => `Investor Visa to ${c}`,
    organization: (c) => `Investment Authority - ${c}`,
    degreeLevel: "Not required",
    field: "Investment",
    funding: "Self-Funded",
    amount: "استثمار بحد أدنى",
    duration: "إقامة قابلة للتجديد ومسار للجنسية",
    benefits: ["إقامة طويلة الأمد", "إمكانية الحصول على الجنسية", "حق إحضار العائلة", "ميزات ضريبية"],
    requirements: ["استثمار بحد أدنى محدد (يختلف حسب البلد)", "إثبات مصدر الأموال", "خطة عمل (لبعض البرامج)", "السجل الجنائي خالٍ"],
    tags: ["استثمار", "جنسية", "أعمال"],
    description: (c) => `برنامج إقامة عبر الاستثمار في ${c}، يتيح للمستثمرين الحصول على إقامة طويلة الأمد ومسار للجنسية.`,
    eligibility: "المستثمرون ورجال الأعمال الراغبون في توطين رأسمالهم في ${c}.",
    acceptanceRate: 75,
    difficulty: 2,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة الباحث عن عمل في ${c}`,
    title: (c) => `Job Seeker Visa to ${c}`,
    organization: (c) => `Labour Department - ${c}`,
    degreeLevel: "Bachelor or higher",
    field: "Job Search",
    funding: "Self-Funded",
    amount: "غير ممول",
    duration: "6-18 شهراً",
    benefits: ["إقامة مؤقتة للبحث عن عمل", "حق الانتقال لتأشيرة عمل عند توقيع عقد", "وصول لخدمات الاستشارة المهنية"],
    requirements: ["شهادة جامعية معادلة", "إثبات قدرة مالية للإقامة (8000-12000$)", "تأمين صحي", "اختبار اللغة"],
    tags: ["بحث عن عمل", "إقامة مؤقتة", "خريج"],
    description: (c) => `تأشيرة تتيح الإقامة في ${c} لمدة محددة للبحث عن فرصة عمل، مع إمكانية الانتقال لتأشيرة عمل عند توقيع عقد.`,
    eligibility: "خريجو الجامعات الباحثون عن فرصة عمل في القطاعات ذات الطلب.",
    acceptanceRate: 45,
    difficulty: 3,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة العمل الموسمي في ${c}`,
    title: (c) => `Seasonal Work Visa to ${c}`,
    organization: (c) => `Labour Ministry - ${c}`,
    degreeLevel: "Not required",
    field: "Seasonal Work",
    funding: "Self-Funded",
    amount: "بدون رسوم منحة",
    duration: "3-9 أشهر",
    benefits: ["دخل قانوني", "خبرة دولية", "إقامة قانونية مؤقتة"],
    requirements: ["عرض عمل موسمي مسبق", "السن 18-35 (في بعض البرامج)", "صحة جيدة"],
    tags: ["عمل موسمي", "زراعة", "سياحة"],
    description: (c) => `برنامج عمل موسمي في ${c} موجه نحو القطاع الزراعي والسياحي، يقدم دخلاً وخبرة قصيرة الأمد.`,
    eligibility: "الراغبون في فرص عمل قصيرة الأمد ضمن قطاعات معينة.",
    acceptanceRate: 55,
    difficulty: 2,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة لم شمل العائلة إلى ${c}`,
    title: (c) => `Family Reunification Visa to ${c}`,
    organization: (c) => `Civil Registry - ${c}`,
    degreeLevel: "Not required",
    field: "Family",
    funding: "Self-Funded",
    amount: "غير ممول",
    duration: "إقامة طويلة الأمد",
    benefits: ["لم شمل العائلة", "إقامة قانونية", "حق العمل للزوج/الزوجة", "مسار للإقامة الدائمة"],
    requirements: ["وجود قريب مقيم في ${c} (زوج/زوجة، أطفال، والدين)", "إثبات صلة القرابة", "إثبات قدرة الكفيل المالية"],
    tags: ["عائلة", "لم شمل", "إقامة"],
    description: (c) => `تأشيرة تتيح الانضمام إلى أحد أفراد العائلة المقيم في ${c} عبر مسارات قانونية واضحة.`,
    eligibility: "الزوجات/الأزواج، الأبناء القاصرون، والوالدون لمقيمين شرعيين.",
    acceptanceRate: 70,
    difficulty: 2,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة ريادة الأعمال إلى ${c}`,
    title: (c) => `Startup / Entrepreneur Visa to ${c}`,
    organization: (c) => `Startup Hub - ${c}`,
    degreeLevel: "Not required",
    field: "Entrepreneurship",
    funding: "Self-Funded",
    amount: "خطة عمل + استثمار جزئي",
    duration: "2-4 سنوات",
    benefits: ["إقامة طويلة الأمد", "دعم لإطلاق المشروع", "وصول لمستثمرين"],
    requirements: ["خطة عمل احترافية", "خبرة سابقة في المجال", "استثمار جزئي", "موافقة مسرّع أعمال"],
    tags: ["ريادة أعمال", "ستارت أب", "استثمار"],
    description: (c) => `تأشيرة لرواد الأعمال الراغبين في إطلاق شركة ناشئة في ${c}، مع دعم من مسرعات الأعمال.`,
    eligibility: "رواد الأعمال أصحاب الأفكار المبتكرة، خصوصاً في التكنولوجيا والصحة.",
    acceptanceRate: 30,
    difficulty: 4,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة الدراسة مع حق العمل في ${c}`,
    title: (c) => `Student Visa with Work Rights to ${c}`,
    organization: (c) => `Education Ministry - ${c}`,
    degreeLevel: "Bachelor / Master",
    field: "Student Migration",
    funding: "Self-Funded",
    amount: "رسوم دراسية معتادة",
    duration: "مدة الدراسة + سنة-سنتان للعمل بعد التخرج",
    benefits: ["إقامة دراسية", "حق العمل بدوام جزئي", "تأشيرة بحث عن عمل بعد التخرج", "مسار للإقامة الدائمة"],
    requirements: ["قبول من جامعة معتمدة", "إثبات مالي", "تأمين صحي", "اختبار اللغة"],
    tags: ["دراسة", "عمل أثناء الدراسة", "خريج"],
    description: (c) => `مسار دراسي يتيح للطلاب الدوليين الدراسة في ${c} مع حق العمل أثناء الدراسة وفرصة الإقامة بعد التخرج.`,
    eligibility: "الطلاب المقبولون في جامعات معتمدة في ${c}.",
    acceptanceRate: 65,
    difficulty: 3,
  },
  {
    type: "migration",
    titleAr: (c) => `برنامج التطوع الدولي في ${c}`,
    title: (c) => `International Volunteer Program in ${c}`,
    organization: (c) => `Cultural Exchange - ${c}`,
    degreeLevel: "Not required",
    field: "Volunteer Work",
    funding: "Partial",
    amount: "إقامة وطعام مدعوم",
    duration: "3-12 شهراً",
    benefits: ["إقامة وطعام", "خبرة دولية", "تطوير المهارات", "شهادة معتمدة"],
    requirements: ["السن 18-35", "إتقان لغة بسيط", "حماس للعمل التطوعي"],
    tags: ["تطوع", "تبادل ثقافي", "قصير الأمد"],
    description: (c) => `برنامج تطوع دولي في ${c} يجمع بين الخبرة الثقافية وخدمة المجتمع المحلي.`,
    eligibility: "الشباب المهتمون بالعمل التطوعي والتبادل الثقافي.",
    acceptanceRate: 50,
    difficulty: 2,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة العمل الحر إلى ${c}`,
    title: (c) => `Freelancer Visa to ${c}`,
    organization: (c) => `Self-Employment Office - ${c}`,
    degreeLevel: "Not required",
    field: "Freelance",
    funding: "Self-Funded",
    amount: "إثبات دخل ذاتي",
    duration: "1-3 سنوات",
    benefits: ["إقامة قانونية", "حق ممارسة المهنة الحرة", "إمكانية تجديد الإقامة", "وصول لخدمات حكومية"],
    requirements: ["إثبات دخل من العمل الحر", "محفظة أعمال", "تأمين صحي", "خبرة في المجال"],
    tags: ["عمل حر", "مستقل", "إقامة"],
    description: (c) => `تأشيرة موجهة للمستقلين والعاملين في المهن الحرة للإقامة في ${c} مع ممارسة نشاطهم.`,
    eligibility: "المستقلون في المجالات الإبداعية والتقنية والاستشارية.",
    acceptanceRate: 40,
    difficulty: 3,
  },
  {
    type: "migration",
    titleAr: (c) => `تأشيرة المتقاعدين إلى ${c}`,
    title: (c) => `Retirement Visa to ${c}`,
    organization: (c) => `Senior Affairs - ${c}`,
    degreeLevel: "Not required",
    field: "Retirement",
    funding: "Self-Funded",
    amount: "إثبات معاش شهري",
    duration: "إقامة طويلة الأمد قابلة للتجديد",
    benefits: ["إقامة هادئة", "تكلفة معيشة منخفضة", "خدمات صحية", "حق الإقامة الدائمة"],
    requirements: ["السن 50-55 فما فوق", "معاش شهري ثابت", "تأمين صحي", "السجل الجنائي خالٍ"],
    tags: ["تقاعد", "إقامة طويلة الأمد"],
    description: (c) => `برنامج إقامة المتقاعدين في ${c}، يقدم بيئة آمنة وخدمات صحية وفرصة للاستمتاع بالحياة في بلد جديد.`,
    eligibility: "المتقاعدون أصحاب المعاشات الثابتة الراغبون في تجربة معيشية جديدة.",
    acceptanceRate: 75,
    difficulty: 1,
  },
];

const TEMPLATES: Template[] = [...SCHOLARSHIP_TEMPLATES, ...MIGRATION_TEMPLATES];

function pickDeadline(seed: number): string {
  // Generate deadlines spread across next 12 months
  const today = new Date();
  const days = (seed * 17 + 30) % 365;
  const date = new Date(today.getFullYear(), today.getMonth(), today.getDate() + days);
  return date.toISOString().slice(0, 10);
}

export function generateOpportunities(countries: InsertCountry[]): InsertOpportunity[] {
  const result: InsertOpportunity[] = [];
  let seed = 1;

  for (const country of countries) {
    for (const tpl of TEMPLATES) {
      // create 1 base opportunity from each template per country
      const featured = (seed % 8) === 0;
      const deadline = pickDeadline(seed);

      const opp: InsertOpportunity = {
        title: tpl.title(country.name),
        titleAr: tpl.titleAr(country.nameAr),
        type: tpl.type,
        countryCode: country.code,
        countryName: country.name,
        countryNameAr: country.nameAr,
        organization: tpl.organization(country.name),
        degreeLevel: tpl.degreeLevel,
        field: tpl.field,
        funding: tpl.funding,
        amount: tpl.amount,
        duration: tpl.duration,
        deadline,
        description: tpl.description(country.nameAr),
        eligibility: tpl.eligibility.replace(/\$\{c\}/g, country.nameAr),
        benefits: tpl.benefits,
        requirements: tpl.requirements,
        applicationUrl: `https://example.com/apply/${country.code.toLowerCase()}/${seed}`,
        tags: [country.region, ...tpl.tags],
        difficulty: tpl.difficulty,
        acceptanceRate: tpl.acceptanceRate,
        featured,
        affiliateUrl: featured ? `https://partner.example.com/${country.code.toLowerCase()}/${seed}` : null,
      };
      result.push(opp);
      seed++;
    }
  }

  // Add a handful of well-known specific opportunities for popular countries to feel real
  const SPECIFIC: Array<Partial<InsertOpportunity> & Pick<InsertOpportunity, "countryCode" | "title" | "titleAr" | "type" | "deadline" | "description" | "organization" | "degreeLevel" | "field" | "funding">> = [
    {
      countryCode: "GB", title: "Chevening Scholarship", titleAr: "منحة شيفنينغ",
      type: "scholarship", organization: "UK Government - FCDO",
      degreeLevel: "Master", field: "All Fields", funding: "Full Funding",
      amount: "تمويل كامل + بدل معيشة", duration: "سنة",
      deadline: "2026-11-05",
      description: "منحة شيفنينغ المرموقة من الحكومة البريطانية لقادة المستقبل، تغطي الرسوم وبدل المعيشة في أي جامعة بريطانية.",
      benefits: ["رسوم دراسية كاملة", "بدل معيشة شهري", "تذاكر طيران", "بدل الكتب والأبحاث"],
      requirements: ["خبرة عمل سنتان", "بكالوريوس بدرجة 2:1", "قبول جامعي", "خطابات توصية"],
      tags: ["تمويل كامل", "ماجستير", "بريطانيا", "شيفنينغ"],
      featured: true, acceptanceRate: 5, difficulty: 5,
    },
    {
      countryCode: "DE", title: "DAAD Scholarship", titleAr: "منحة DAAD الألمانية",
      type: "scholarship", organization: "DAAD - German Academic Exchange",
      degreeLevel: "Master / PhD", field: "All Fields", funding: "Full Funding",
      amount: "934-1300€ شهرياً", duration: "1-3 سنوات",
      deadline: "2026-10-15",
      description: "منحة DAAD الألمانية للماجستير والدكتوراه في مختلف التخصصات، توفر بدل معيشة شهري وتأمين صحي.",
      benefits: ["بدل معيشة شهري ممتاز", "تأمين صحي", "بدل سفر", "بدل أبحاث"],
      requirements: ["بكالوريوس متفوق", "إجادة الإنجليزية أو الألمانية", "خطة دراسية"],
      tags: ["تمويل كامل", "ألمانيا", "DAAD", "ماجستير", "دكتوراه"],
      featured: true, acceptanceRate: 8, difficulty: 5,
    },
    {
      countryCode: "FR", title: "Eiffel Excellence Scholarship", titleAr: "منحة إيفل للتميز",
      type: "scholarship", organization: "Campus France",
      degreeLevel: "Master / PhD", field: "Engineering, Economics, Law, Political Science",
      funding: "Full Funding",
      amount: "1181-1700€ شهرياً", duration: "1-3 سنوات",
      deadline: "2027-01-10",
      description: "منحة فرنسية مرموقة للطلاب الأجانب المتفوقين لمتابعة الماجستير والدكتوراه في فرنسا.",
      benefits: ["بدل شهري", "تذاكر طيران", "تأمين صحي", "تأمين سفر"],
      requirements: ["متقدم من الجامعة الفرنسية", "أقل من 25 سنة (للماجستير)", "تفوق أكاديمي"],
      tags: ["تمويل كامل", "فرنسا", "إيفل", "ماجستير"],
      featured: true, acceptanceRate: 7, difficulty: 5,
    },
    {
      countryCode: "AU", title: "Australia Awards Scholarship", titleAr: "جوائز أستراليا",
      type: "scholarship", organization: "Australian Government",
      degreeLevel: "Bachelor / Master / PhD", field: "All Fields",
      funding: "Full Funding",
      amount: "تمويل كامل", duration: "حتى 4 سنوات",
      deadline: "2026-04-30",
      description: "منحة أستراليا الحكومية للطلاب من الدول النامية للدراسة في أعرق الجامعات الأسترالية.",
      benefits: ["رسوم دراسية كاملة", "بدل معيشة", "تذاكر سفر", "تأمين صحي شامل"],
      requirements: ["جنسية من دولة مؤهلة", "خبرة عملية", "خطة العودة للوطن"],
      tags: ["تمويل كامل", "أستراليا", "جوائز", "Australia Awards"],
      featured: true, acceptanceRate: 12, difficulty: 4,
    },
    {
      countryCode: "JP", title: "MEXT Scholarship", titleAr: "منحة MEXT اليابانية",
      type: "scholarship", organization: "MEXT - Government of Japan",
      degreeLevel: "Bachelor / Master / PhD", field: "All Fields",
      funding: "Full Funding",
      amount: "117,000-145,000 ين شهرياً", duration: "5-7 سنوات",
      deadline: "2026-06-15",
      description: "منحة الحكومة اليابانية الكاملة للطلاب الأجانب، تشمل اللغة اليابانية ودراسات متقدمة.",
      benefits: ["بدل شهري", "رسوم دراسية", "تذاكر سفر", "دروس لغة يابانية"],
      requirements: ["شهادة سابقة", "اختبار اللغة اليابانية أو الإنجليزية", "اختبار قبول"],
      tags: ["تمويل كامل", "اليابان", "MEXT"],
      featured: true, acceptanceRate: 10, difficulty: 5,
    },
    {
      countryCode: "KR", title: "Global Korea Scholarship (GKS)", titleAr: "منحة كوريا العالمية",
      type: "scholarship", organization: "NIIED - Korean Government",
      degreeLevel: "Bachelor / Master / PhD", field: "All Fields",
      funding: "Full Funding",
      amount: "تمويل كامل", duration: "2-7 سنوات",
      deadline: "2026-09-30",
      description: "منحة الحكومة الكورية الكاملة للطلاب الأجانب في أرقى جامعات كوريا الجنوبية.",
      benefits: ["رسوم دراسية", "بدل معيشة", "تذاكر سفر", "دروس لغة كورية", "تأمين صحي"],
      requirements: ["شهادة سابقة بمعدل عالٍ", "اختبار اللغة (TOPIK أو IELTS)", "خطاب الدوافع"],
      tags: ["تمويل كامل", "كوريا الجنوبية", "GKS"],
      featured: true, acceptanceRate: 15, difficulty: 4,
    },
    {
      countryCode: "CA", title: "Express Entry - Federal Skilled Worker", titleAr: "Express Entry - برنامج العمالة الماهرة الفيدرالي",
      type: "migration", organization: "IRCC - Government of Canada",
      degreeLevel: "Bachelor or higher", field: "Skilled Migration",
      funding: "Self-Funded",
      amount: "غير ممول", duration: "إقامة دائمة",
      deadline: "2027-12-31",
      description: "النظام الكندي الإلكتروني للهجرة الماهرة عبر نقاط CRS، يتيح الحصول على الإقامة الدائمة في كندا.",
      benefits: ["إقامة دائمة", "حق العمل الكامل", "خدمات صحية مجانية", "مسار للجنسية بعد 3 سنوات"],
      requirements: ["نقاط CRS كافية", "اختبار IELTS/CELPIP", "تقييم شهادات أكاديمية", "خبرة عمل ماهرة"],
      tags: ["كندا", "Express Entry", "إقامة دائمة", "عمل ماهر"],
      featured: true, acceptanceRate: 32, difficulty: 4,
    },
    {
      countryCode: "AU", title: "Skilled Independent Visa (Subclass 189)", titleAr: "تأشيرة الهجرة الماهرة المستقلة (189)",
      type: "migration", organization: "Department of Home Affairs - Australia",
      degreeLevel: "Bachelor or higher", field: "Skilled Migration",
      funding: "Self-Funded",
      amount: "غير ممول", duration: "إقامة دائمة",
      deadline: "2027-06-30",
      description: "تأشيرة أسترالية للمهاجرين المهرة بدون كفيل، تمنح الإقامة الدائمة عبر نظام النقاط.",
      benefits: ["إقامة دائمة", "حق العمل الكامل", "Medicare", "مسار للجنسية بعد 4 سنوات"],
      requirements: ["مهنة ضمن قائمة المهن المطلوبة", "65 نقطة فأكثر", "تقييم مهاراتك", "اختبار اللغة الإنجليزية"],
      tags: ["أستراليا", "189", "إقامة دائمة", "عمل ماهر"],
      featured: true, acceptanceRate: 25, difficulty: 4,
    },
    {
      countryCode: "DE", title: "EU Blue Card - Germany", titleAr: "البطاقة الزرقاء الأوروبية - ألمانيا",
      type: "migration", organization: "Federal Office for Migration - Germany",
      degreeLevel: "Bachelor or higher", field: "High-skilled Work",
      funding: "Self-Funded",
      amount: "راتب أدنى محدد", duration: "4 سنوات قابلة للتجديد",
      deadline: "2027-12-31",
      description: "البطاقة الزرقاء الأوروبية في ألمانيا للعمالة الماهرة، تتيح إقامة طويلة وفرصة لجلب العائلة.",
      benefits: ["إقامة عمل لمدة 4 سنوات", "مسار للإقامة الدائمة بعد 21-33 شهراً", "حق إحضار العائلة فوراً", "حرية التنقل في الاتحاد الأوروبي"],
      requirements: ["شهادة جامعية معترف بها", "عقد عمل في تخصصك", "حد أدنى للراتب (~58,400€ سنوياً)"],
      tags: ["ألمانيا", "EU Blue Card", "إقامة"],
      featured: true, acceptanceRate: 70, difficulty: 3,
    },
    {
      countryCode: "PT", title: "Portugal D7 Visa", titleAr: "تأشيرة البرتغال D7",
      type: "migration", organization: "SEF - Portugal Immigration",
      degreeLevel: "Not required", field: "Passive Income / Retirement",
      funding: "Self-Funded",
      amount: "إثبات دخل سلبي شهري", duration: "إقامة سنتين قابلة للتجديد",
      deadline: "2027-12-31",
      description: "تأشيرة D7 البرتغالية لأصحاب الدخل السلبي والمتقاعدين، تفتح الباب للجنسية البرتغالية بعد 5 سنوات.",
      benefits: ["إقامة في الاتحاد الأوروبي", "مسار للجنسية بعد 5 سنوات", "حق إحضار العائلة", "نظام ضريبي مميز للوافدين"],
      requirements: ["دخل شهري ثابت (820€+)", "مسكن في البرتغال", "تأمين صحي", "السجل الجنائي خالٍ"],
      tags: ["البرتغال", "D7", "إقامة"],
      featured: true, acceptanceRate: 80, difficulty: 2,
    },
    {
      countryCode: "AE", title: "UAE Golden Visa", titleAr: "تأشيرة الإمارات الذهبية",
      type: "migration", organization: "Federal Authority for Identity & Citizenship - UAE",
      degreeLevel: "Varies", field: "Talent / Investment",
      funding: "Self-Funded",
      amount: "حسب الفئة", duration: "5-10 سنوات قابلة للتجديد",
      deadline: "2027-12-31",
      description: "إقامة ذهبية في الإمارات للمواهب والمستثمرين والمهنيين المتميزين، 10 سنوات قابلة للتجديد بدون كفيل.",
      benefits: ["إقامة طويلة بدون كفيل", "حق إحضار العائلة بدون قيد عمر", "حق ملكية كاملة للأعمال", "إقامة لخادمة المنزل"],
      requirements: ["إنجاز استثنائي / مؤهلات / استثمار", "شهادة جامعية أو خبرة استثنائية"],
      tags: ["الإمارات", "ذهبية", "إقامة طويلة"],
      featured: true, acceptanceRate: 60, difficulty: 3,
    },
  ];

  for (const s of SPECIFIC) {
    const country = countries.find((c) => c.code === s.countryCode);
    if (!country) continue;
    result.push({
      title: s.title,
      titleAr: s.titleAr,
      type: s.type,
      countryCode: country.code,
      countryName: country.name,
      countryNameAr: country.nameAr,
      organization: s.organization,
      degreeLevel: s.degreeLevel,
      field: s.field,
      funding: s.funding,
      amount: s.amount,
      duration: s.duration,
      deadline: s.deadline,
      description: s.description,
      eligibility: s.eligibility ?? "",
      benefits: s.benefits ?? [],
      requirements: s.requirements ?? [],
      applicationUrl: `https://example.com/apply/${country.code.toLowerCase()}/featured`,
      tags: s.tags ?? [],
      difficulty: s.difficulty ?? 4,
      acceptanceRate: s.acceptanceRate ?? 20,
      featured: s.featured ?? true,
      affiliateUrl: `https://partner.example.com/${country.code.toLowerCase()}/featured`,
    });
  }

  return result;
}
